#!/bin/bash

DB_NAME1="sandeep4_virtual"
OUT_FILE_NAME="labbackup"
VERSION="v1.0.4"
OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"

# take the dump
mysqldump $DB_NAME1 > $DB_NAME1.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while taking db dump."
  echo "Aborting backup."
  exit 1;
fi

# tar the $DB_NAME folder
tar cfvz $OUT_FILE $DB_NAME1.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while tar-ing the dump."
  echo "Aborting backup."
  exit 1;
fi

#clean up data
rm $DB_NAME1.sql
echo "Backup successful."

exit 0;
